### ISSUE TITLE
OpenGL.error.GLError

### ISSUE THREAD

**Issue by Jaraxxus-Me** [r-pad/OSSID_code#1]
OpenGL.error.GLError: GLError(
        err = 12297,
        baseOperation = eglCreateContext,
        cArguments = (
                <OpenGL._opaque.EGLDisplay_pointer object at 0x7fb5a03692c0>,
                <OpenGL._opaque.EGLConfig_pointer object at 0x7fb5a5d18b40>,
                <OpenGL._opaque.EGLContext_pointer object at 0x7fb531115540>,
                <OpenGL.arrays.lists.c_int_Array_7 object at 0x7fb5a5d180c0>,
        ),
        result = <OpenGL._opaque.EGLContext_pointer object at 0x7fb5a5bf53c0>
)

I got this error when running:
python online_learning.py \
    --dataset_name lmo \
    --n_local_test 10 \
    --finetune_interval 32 \
    --finetune_epochs 1 \
    --always_dtoid_mask \
    --use_pretrained_dtoid \
    --exp_name lmo_final_main

How to fix this?

**Comment by georgegu1997** [comment]
@Jaraxxus-Me and I have fixed this issue together: 

This bug may be because you want to run the renderer on a machine without a monitor (offscreen rendering). 

1. Install OSmesa following the instructions [here](https://pyrender.readthedocs.io/en/latest/install/index.html#getting-pyrender-working-with-osmesa). 
2. Change [this line](https://pyrender.readthedocs.io/en/latest/install/index.html#getting-pyrender-working-with-osmesa) to 
```
os.environ['PYOPENGL_PLATFORM'] = 'osmesa'
```

Thanks @Jaraxxus-Me for solving this out!
